/**
 * Builds external/ts-mls.js — the vendored MLS bundle used by group chat.
 *
 *   npm install && npm run build:mls
 *
 * The client has no build step for application code; third-party libraries are
 * committed under external/ (see noble-*.js). This script produces that
 * artifact so the vendored file is reproducible rather than mystery bytes.
 *
 * Pinned to the hybrid post-quantum ciphersuite
 * MLS_256_XWING_CHACHA20POLY1305_SHA512_Ed25519 (X25519 + ML-KEM-768), which
 * matches the KDF(ECDH || ML-KEM) construction already used for 1:1 chat.
 *
 * Deliberately does NOT bundle ML-KEM, HKDF or ChaCha: crypto.js already
 * provides those (generatePQKeys / pqSharedKey / deriveDhKey / encryptChacha),
 * and reusing them means the post-quantum PSK is sealed to exactly the same
 * ML-KEM-1024 identity as 1:1 chat rather than a second, parallel
 * implementation. Only ed25519 is re-exported, for deriving the MLS signature
 * key from the account's existing pqSeed.
 *
 * NOTE ON VERSIONS: ts-mls pins several peer dependencies to EXACT versions
 * (@noble/ciphers 2.1.1 among them), so package.json pins them to match — do
 * not loosen those to ^ranges or `npm install` will fail to resolve.
 * @noble/hashes is imported by ts-mls but not declared by it, so we depend on
 * it directly.
 */
import { build } from 'esbuild';
import { gzipSync } from 'node:zlib';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outfile = path.join(root, 'external', 'ts-mls.js');
const entry = path.join(root, 'scripts', '.ts-mls-entry.mjs');

// Re-export only what mlsEngine.js needs, so the bundle carries no dead API.
fs.writeFileSync(
  entry,
  `
export * from 'ts-mls';
import '@hpke/chacha20poly1305';
import '@hpke/hybridkem-x-wing';
export { ed25519 } from '@noble/curves/ed25519.js';
`,
);

await build({
  entryPoints: [entry],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  outfile,
  minify: true,
  legalComments: 'none',
  banner: {
    js: '/* ts-mls + X-Wing + ML-KEM-1024 — generated by scripts/build-ts-mls.mjs. Do not edit. */',
  },
  logLevel: 'error',
});

fs.unlinkSync(entry);

const raw = fs.readFileSync(outfile);
console.log(
  `external/ts-mls.js  ${(raw.length / 1024).toFixed(1)} KB raw, ${(gzipSync(raw).length / 1024).toFixed(1)} KB gzip`,
);
